// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGAC.Infrastructure.Data;

#nullable disable

namespace SIGAC.Infrastructure.Migrations
{
    [DbContext(typeof(SigacDbContext))]
    [Migration("20260910210635_AddCheckMotivoAnulacionEntradaInventario")]
    partial class AddCheckMotivoAnulacionEntradaInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGAC.Domain.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_Articulos_Codigo")
                        .HasFilter("[Codigo] IS NOT NULL AND [Codigo] <> ''");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Articulos_Nombre");

                    b.ToTable("Articulos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Articulos_StockActual_NoNegativo", "[StockActual] >= 0");

                            t.HasCheckConstraint("CK_Articulos_StockMinimo_NoNegativo", "[StockMinimo] >= 0");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.AsistenciaComedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("TiempoComida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("TiempoComida");

                    b.HasIndex("BeneficiarioId", "Fecha", "TiempoComida")
                        .IsUnique()
                        .HasDatabaseName("UX_AsistenciasComedor_Beneficiario_Fecha_TiempoComida");

                    b.ToTable("AsistenciasComedor", null, t =>
                        {
                            t.HasCheckConstraint("CK_AsistenciasComedor_TiempoComida", "[TiempoComida] IN ('Desayuno', 'Almuerzo', 'Merienda')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.Beneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumIdentidad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoDocumentoOtro")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Estado");

                    b.HasIndex("NumIdentidad")
                        .IsUnique()
                        .HasDatabaseName("UX_Beneficiarios_NumIdentidad")
                        .HasFilter("[NumIdentidad] IS NOT NULL AND [NumIdentidad] <> ''");

                    b.HasIndex("PrimerNombre", "SegundoNombre", "PrimerApellido", "SegundoApellido", "FechaNacimiento")
                        .IsUnique()
                        .HasDatabaseName("UX_Beneficiarios_Nombres_Apellidos_FechaNacimiento");

                    b.ToTable("Beneficiarios", (string)null);
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DetalleDonacionEspecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DonacionEspecieId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArticulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DonacionEspecieId")
                        .HasDatabaseName("IX_DetallesDonacionEspecie_DonacionEspecie");

                    b.ToTable("DetallesDonacionEspecie", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetallesDonacionEspecie_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_DetallesDonacionEspecie_Categoria", "[Categoria] IN ('Alimento', 'Ropa', 'Calzado', 'Equipo')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionDinero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("DonanteId", "Fecha")
                        .HasDatabaseName("IX_DonacionesDinero_Donante_Fecha");

                    b.ToTable("DonacionesDinero", null, t =>
                        {
                            t.HasCheckConstraint("CK_DonacionesDinero_Monto", "[Monto] > 0");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionEntregada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ComunidadDestinataria")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TipoDestinatario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId")
                        .HasDatabaseName("IX_DonacionesEntregadas_Beneficiario");

                    b.HasIndex("Fecha");

                    b.HasIndex("ArticuloId", "Fecha")
                        .HasDatabaseName("IX_DonacionesEntregadas_Articulo_Fecha");

                    b.ToTable("DonacionesEntregadas", null, t =>
                        {
                            t.HasCheckConstraint("CK_DonacionesEntregadas_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_DonacionesEntregadas_Destinatario", "([TipoDestinatario] = 'Beneficiario' AND [BeneficiarioId] IS NOT NULL AND [ComunidadDestinataria] IS NULL) OR ([TipoDestinatario] = 'Comunidad' AND [ComunidadDestinataria] IS NOT NULL AND [ComunidadDestinataria] <> '' AND [BeneficiarioId] IS NULL)");

                            t.HasCheckConstraint("CK_DonacionesEntregadas_TipoDestinatario", "[TipoDestinatario] IN ('Beneficiario', 'Comunidad')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionEspecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("DonanteId", "Fecha")
                        .HasDatabaseName("IX_DonacionesEspecie_Donante_Fecha");

                    b.ToTable("DonacionesEspecie", (string)null);
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.Donante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Donantes_Nombre");

                    b.ToTable("Donantes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Donantes_TipoPersona", "[TipoPersona] IN ('Física', 'Jurídica')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.EntradaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("DonanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GastoOperativoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DonanteId")
                        .HasDatabaseName("IX_EntradasInventario_Donante");

                    b.HasIndex("Fecha");

                    b.HasIndex("GastoOperativoId")
                        .HasDatabaseName("IX_EntradasInventario_GastoOperativo");

                    b.HasIndex("ArticuloId", "Fecha")
                        .HasDatabaseName("IX_EntradasInventario_Articulo_Fecha");

                    b.ToTable("EntradasInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_EntradasInventario_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_EntradasInventario_MotivoAnulacion", "([Anulada] = 1 AND [MotivoAnulacion] IS NOT NULL) OR ([Anulada] = 0 AND [MotivoAnulacion] IS NULL)");

                            t.HasCheckConstraint("CK_EntradasInventario_Origen", "[Origen] IN ('Donacion', 'Compra')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.GastoOperativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha", "Categoria")
                        .HasDatabaseName("IX_GastosOperativos_Fecha_Categoria");

                    b.ToTable("GastosOperativos", null, t =>
                        {
                            t.HasCheckConstraint("CK_GastosOperativos_Categoria", "[Categoria] IN ('ServiciosBasicos', 'Transporte', 'CompraInsumos', 'Salarios', 'Viaticos')");

                            t.HasCheckConstraint("CK_GastosOperativos_Estado", "[Estado] IN ('Activo', 'Anulado')");

                            t.HasCheckConstraint("CK_GastosOperativos_Monto", "[Monto] > 0");

                            t.HasCheckConstraint("CK_GastosOperativos_MotivoAnulacion", "([Estado] = 'Anulado' AND [MotivoAnulacion] IS NOT NULL) OR ([Estado] <> 'Anulado' AND [MotivoAnulacion] IS NULL)");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.SalidaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ComunidadDestinataria")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("SolicitudPrestamoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSalida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("SolicitudPrestamoId")
                        .IsUnique()
                        .HasDatabaseName("UX_SalidasInventario_SolicitudPrestamo")
                        .HasFilter("[SolicitudPrestamoId] IS NOT NULL");

                    b.HasIndex("ArticuloId", "Fecha")
                        .HasDatabaseName("IX_SalidasInventario_Articulo_Fecha");

                    b.ToTable("SalidasInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalidasInventario_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_SalidasInventario_TipoSalida", "[TipoSalida] IN ('Donacion', 'Prestamo')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.SolicitudPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actividad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("Estado");

                    b.HasIndex("Fecha");

                    b.ToTable("SolicitudesPrestamo", null, t =>
                        {
                            t.HasCheckConstraint("CK_SolicitudesPrestamo_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_SolicitudesPrestamo_Estado", "[Estado] IN ('Pendiente', 'Aprobada', 'Rechazada')");
                        });
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.AsistenciaComedor", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DetalleDonacionEspecie", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.DonacionEspecie", "DonacionEspecie")
                        .WithMany("Detalles")
                        .HasForeignKey("DonacionEspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonacionEspecie");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionDinero", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Donante", "Donante")
                        .WithMany()
                        .HasForeignKey("DonanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donante");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionEntregada", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGAC.Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Articulo");

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionEspecie", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Donante", "Donante")
                        .WithMany()
                        .HasForeignKey("DonanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donante");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.EntradaInventario", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGAC.Domain.Entities.Donante", null)
                        .WithMany()
                        .HasForeignKey("DonanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGAC.Domain.Entities.GastoOperativo", null)
                        .WithMany()
                        .HasForeignKey("GastoOperativoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.SalidaInventario", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGAC.Domain.Entities.SolicitudPrestamo", null)
                        .WithMany()
                        .HasForeignKey("SolicitudPrestamoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.SolicitudPrestamo", b =>
                {
                    b.HasOne("SIGAC.Domain.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SIGAC.Domain.Entities.DonacionEspecie", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
