namespace SIGAC.Services;

// Solo para el selector visual de código de país del teléfono (ver
// Components/Shared/PhoneInput.razor). El número que se guarda sigue siendo
// únicamente el local: SIGAC opera en Costa Rica y esa validación (8 dígitos)
// no cambia, ver ReglasBeneficiario.DigitosTelefono.
public sealed record Pais(string Nombre, string Iso2, string CodigoTelefono)
{
    public string Bandera => ConvertirABandera(Iso2);

    // La bandera es la combinación de dos "regional indicator symbols"
    // (U+1F1E6 = 'A'): no hace falta una imagen por país, la fuente del
    // sistema ya sabe dibujar el emoji a partir del código ISO.
    private static string ConvertirABandera(string iso2)
    {
        if (iso2.Length != 2)
        {
            return string.Empty;
        }

        var primero = char.ConvertFromUtf32(0x1F1E6 + (char.ToUpperInvariant(iso2[0]) - 'A'));
        var segundo = char.ConvertFromUtf32(0x1F1E6 + (char.ToUpperInvariant(iso2[1]) - 'A'));
        return primero + segundo;
    }
}

public static class Paises
{
    public static readonly Pais CostaRica = new("Costa Rica", "CR", "506");

    public static readonly IReadOnlyList<Pais> Todos = new List<Pais>
    {
        new("Afganistán", "AF", "93"),
        new("Albania", "AL", "355"),
        new("Alemania", "DE", "49"),
        new("Andorra", "AD", "376"),
        new("Angola", "AO", "244"),
        new("Antigua y Barbuda", "AG", "1268"),
        new("Arabia Saudita", "SA", "966"),
        new("Argelia", "DZ", "213"),
        new("Argentina", "AR", "54"),
        new("Armenia", "AM", "374"),
        new("Australia", "AU", "61"),
        new("Austria", "AT", "43"),
        new("Azerbaiyán", "AZ", "994"),
        new("Bahamas", "BS", "1242"),
        new("Bangladés", "BD", "880"),
        new("Barbados", "BB", "1246"),
        new("Baréin", "BH", "973"),
        new("Bélgica", "BE", "32"),
        new("Belice", "BZ", "501"),
        new("Benín", "BJ", "229"),
        new("Bielorrusia", "BY", "375"),
        new("Birmania", "MM", "95"),
        new("Bolivia", "BO", "591"),
        new("Bosnia y Herzegovina", "BA", "387"),
        new("Botsuana", "BW", "267"),
        new("Brasil", "BR", "55"),
        new("Brunéi", "BN", "673"),
        new("Bulgaria", "BG", "359"),
        new("Burkina Faso", "BF", "226"),
        new("Burundi", "BI", "257"),
        new("Bután", "BT", "975"),
        new("Cabo Verde", "CV", "238"),
        new("Camboya", "KH", "855"),
        new("Camerún", "CM", "237"),
        new("Canadá", "CA", "1"),
        new("Catar", "QA", "974"),
        new("Chad", "TD", "235"),
        new("Chequia", "CZ", "420"),
        new("Chile", "CL", "56"),
        new("China", "CN", "86"),
        new("Chipre", "CY", "357"),
        new("Ciudad del Vaticano", "VA", "379"),
        new("Colombia", "CO", "57"),
        new("Comoras", "KM", "269"),
        new("Corea del Norte", "KP", "850"),
        new("Corea del Sur", "KR", "82"),
        CostaRica,
        new("Croacia", "HR", "385"),
        new("Cuba", "CU", "53"),
        new("Dinamarca", "DK", "45"),
        new("Dominica", "DM", "1767"),
        new("Ecuador", "EC", "593"),
        new("Egipto", "EG", "20"),
        new("El Salvador", "SV", "503"),
        new("Emiratos Árabes Unidos", "AE", "971"),
        new("Eritrea", "ER", "291"),
        new("Eslovaquia", "SK", "421"),
        new("Eslovenia", "SI", "386"),
        new("España", "ES", "34"),
        new("Estados Unidos", "US", "1"),
        new("Estonia", "EE", "372"),
        new("Esuatini", "SZ", "268"),
        new("Etiopía", "ET", "251"),
        new("Filipinas", "PH", "63"),
        new("Fiyi", "FJ", "679"),
        new("Finlandia", "FI", "358"),
        new("Francia", "FR", "33"),
        new("Gabón", "GA", "241"),
        new("Gambia", "GM", "220"),
        new("Georgia", "GE", "995"),
        new("Ghana", "GH", "233"),
        new("Granada", "GD", "1473"),
        new("Grecia", "GR", "30"),
        new("Guatemala", "GT", "502"),
        new("Guinea", "GN", "224"),
        new("Guinea-Bisáu", "GW", "245"),
        new("Guinea Ecuatorial", "GQ", "240"),
        new("Guyana", "GY", "592"),
        new("Haití", "HT", "509"),
        new("Honduras", "HN", "504"),
        new("Hungría", "HU", "36"),
        new("India", "IN", "91"),
        new("Indonesia", "ID", "62"),
        new("Irak", "IQ", "964"),
        new("Irán", "IR", "98"),
        new("Irlanda", "IE", "353"),
        new("Islandia", "IS", "354"),
        new("Islas Marshall", "MH", "692"),
        new("Islas Salomón", "SB", "677"),
        new("Israel", "IL", "972"),
        new("Italia", "IT", "39"),
        new("Jamaica", "JM", "1876"),
        new("Japón", "JP", "81"),
        new("Jordania", "JO", "962"),
        new("Kazajistán", "KZ", "7"),
        new("Kenia", "KE", "254"),
        new("Kirguistán", "KG", "996"),
        new("Kiribati", "KI", "686"),
        new("Kuwait", "KW", "965"),
        new("Laos", "LA", "856"),
        new("Lesoto", "LS", "266"),
        new("Letonia", "LV", "371"),
        new("Líbano", "LB", "961"),
        new("Liberia", "LR", "231"),
        new("Libia", "LY", "218"),
        new("Liechtenstein", "LI", "423"),
        new("Lituania", "LT", "370"),
        new("Luxemburgo", "LU", "352"),
        new("Macedonia del Norte", "MK", "389"),
        new("Madagascar", "MG", "261"),
        new("Malasia", "MY", "60"),
        new("Malaui", "MW", "265"),
        new("Maldivas", "MV", "960"),
        new("Malí", "ML", "223"),
        new("Malta", "MT", "356"),
        new("Marruecos", "MA", "212"),
        new("Mauricio", "MU", "230"),
        new("Mauritania", "MR", "222"),
        new("México", "MX", "52"),
        new("Micronesia", "FM", "691"),
        new("Moldavia", "MD", "373"),
        new("Mónaco", "MC", "377"),
        new("Mongolia", "MN", "976"),
        new("Montenegro", "ME", "382"),
        new("Mozambique", "MZ", "258"),
        new("Namibia", "NA", "264"),
        new("Nauru", "NR", "674"),
        new("Nepal", "NP", "977"),
        new("Nicaragua", "NI", "505"),
        new("Níger", "NE", "227"),
        new("Nigeria", "NG", "234"),
        new("Noruega", "NO", "47"),
        new("Nueva Zelanda", "NZ", "64"),
        new("Omán", "OM", "968"),
        new("Países Bajos", "NL", "31"),
        new("Pakistán", "PK", "92"),
        new("Palaos", "PW", "680"),
        new("Panamá", "PA", "507"),
        new("Papúa Nueva Guinea", "PG", "675"),
        new("Paraguay", "PY", "595"),
        new("Perú", "PE", "51"),
        new("Polonia", "PL", "48"),
        new("Portugal", "PT", "351"),
        new("Reino Unido", "GB", "44"),
        new("República Centroafricana", "CF", "236"),
        new("República Democrática del Congo", "CD", "243"),
        new("República Dominicana", "DO", "1"),
        new("Congo", "CG", "242"),
        new("Ruanda", "RW", "250"),
        new("Rumania", "RO", "40"),
        new("Rusia", "RU", "7"),
        new("Samoa", "WS", "685"),
        new("San Cristóbal y Nieves", "KN", "1869"),
        new("San Marino", "SM", "378"),
        new("San Vicente y las Granadinas", "VC", "1784"),
        new("Santa Lucía", "LC", "1758"),
        new("Santo Tomé y Príncipe", "ST", "239"),
        new("Senegal", "SN", "221"),
        new("Serbia", "RS", "381"),
        new("Seychelles", "SC", "248"),
        new("Sierra Leona", "SL", "232"),
        new("Singapur", "SG", "65"),
        new("Siria", "SY", "963"),
        new("Somalia", "SO", "252"),
        new("Sri Lanka", "LK", "94"),
        new("Sudáfrica", "ZA", "27"),
        new("Sudán", "SD", "249"),
        new("Sudán del Sur", "SS", "211"),
        new("Suecia", "SE", "46"),
        new("Suiza", "CH", "41"),
        new("Surinam", "SR", "597"),
        new("Tailandia", "TH", "66"),
        new("Taiwán", "TW", "886"),
        new("Tanzania", "TZ", "255"),
        new("Tayikistán", "TJ", "992"),
        new("Timor Oriental", "TL", "670"),
        new("Togo", "TG", "228"),
        new("Tonga", "TO", "676"),
        new("Trinidad y Tobago", "TT", "1868"),
        new("Túnez", "TN", "216"),
        new("Turkmenistán", "TM", "993"),
        new("Turquía", "TR", "90"),
        new("Tuvalu", "TV", "688"),
        new("Ucrania", "UA", "380"),
        new("Uganda", "UG", "256"),
        new("Uruguay", "UY", "598"),
        new("Uzbekistán", "UZ", "998"),
        new("Vanuatu", "VU", "678"),
        new("Venezuela", "VE", "58"),
        new("Vietnam", "VN", "84"),
        new("Yemen", "YE", "967"),
        new("Yibuti", "DJ", "253"),
        new("Zambia", "ZM", "260"),
        new("Zimbabue", "ZW", "263"),
    }.OrderBy(p => p.Nombre, StringComparer.OrdinalIgnoreCase).ToList();
}
